belkarta_companies:
    path:     /catalog/{page}/{type}/{city}
    defaults: { _controller: BelkartaCompanyBundle:Default:index, type: 'all', city: 'all' }

belkarta_company_new:
    path:     /company/new
    defaults: { _controller: BelkartaCompanyBundle:Default:create }

belkarta_company_created:
    path: /company/created
    defaults: { _controller: BelkartaCompanyBundle:Default:created }

belkarta_company:
    path:     /company/{id}
    defaults: { _controller: BelkartaCompanyBundle:Default:company }
