<?php

namespace Files\ImagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandLogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandLogoRepository extends EntityRepository
{
}
