upload_company_logo:
    path:     /files/upload/logo/brand/{id}
    defaults: { _controller: FilesImagesBundle:Default:uploadBrandLogo }

upload_image:
    path:     /files/upload/image
    defaults: { _controller: FilesImagesBundle:Default:uploadImage }
